### ISSUE TITLE
Unable to create custom hook

### ISSUE THREAD

**Issue by blueyed** [getsentry/zeus#113]
I am trying to create a custom hook via https://zeus.ci/gh/neomake/neomake/settings/hooks/create, but only get an "An error occurred." notification in the lower right.

I've been able to create the hook for Travis CI and it seems this can be used manually, however POSTing to `$ZEUS_HOOK_BASE/builds/X` has `"provider": "travis"` in the response then - not sure how relevant this is.

**Comment by dcramer** [comment]
https://sentry.io/sentry/zeus/issues/534430104/
