### ISSUE TITLE
Uploading webpack-stats.json doesn't update total_asset_size for revision

### ISSUE THREAD

**Issue by chdsbd** [getsentry/zeus#176]
I can't get zeus to update the bundle stats for a revision.

I've used the zeus cli to upload a webpack-stats.json file via the following command:

```console
$ zeus upload webpack-stats.json  --job "$CIRCLE_BUILD_NUM" --build="$CIRCLE_WORKFLOW_ID" --type='application/webpack-stats+json'
info:    Artifact upload completed
info:    URL: https://zeus.ci/api/repos/gh/recipeyak/recipeyak/builds/1/jobs/1/artifacts/16add888-2d63-11e9-a460-0a580a281406/download
```

But an API call to `https://zeus.ci/api/repos/gh/recipeyak/recipeyak/revisions/d5e9fa82c95e22538072632bacc8fee5221c70d9/bundle-stats` returns `[]`.

I would have expected that zeus would process the stats file and update the bundle size associated with a revision.

I'm using `webpack@^3.5.6` with `webpack-bundle-analyzer@^3.0.3`.

**Comment by dcramer** [comment]
I've noticed some odd behavior with how the webpack stats work. It's possible we're doing things completely wrong. When I built it the format didn't seem fully (or correctly) documented.

https://github.com/getsentry/zeus/blob/master/zeus/artifacts/webpack.py#L20

I know in some of our test it didn't give us the data we expected of it.

**Comment by chdsbd** [comment]
Update, I tested locally with my webpack stats json file and webpack.py isn't happy. I'm going to try and figure out what's going on.

```
tests/zeus/artifacts/test_webpack.py:33: in test_result_generation_chris
    handler.process(fp)
zeus/artifacts/webpack.py:49: in process
    asset = asset_index[asset_name]
E   KeyError: 'static/css/main.900e26e0.css'
```
