### ISSUE TITLE
Zeus down ?

### ISSUE THREAD

**Issue by pitpit** [getsentry/zeus#188]
Hi,

I've got following error when trying to create a build onto zeus.ci:
```
error:   Job update failed: 502 Bad Gateway
```

**Comment by untitaker** [comment]
We're painfully aware. Hopefully Zeus will receive more attention as we start using it for more stuff internally.

**Comment by dcramer** [comment]
tl;dr is we think git is unhappy with how we have attempted to underprovision resources for web nodes

**Comment by dcramer** [comment]
Spending some more time on this over the holidays, though given this ticket is generic and we've made a bunch of stability fixes I'm going to close it out.
