### ISSUE TITLE
https://zeus.ci is down.

### ISSUE THREAD

**Issue by kitsunde** [getsentry/zeus#25]
<img width="861" alt="screenshot 2017-09-30 05 43 04" src="https://user-images.githubusercontent.com/48965/31037229-86b9bace-a5a2-11e7-9217-dea8b386eb9e.png">

**Comment by dcramer** [comment]
in kubernetes hell rn

im reverting to pre-enforce-ssl since im having an awful time debugging what wrong in prod, and will take a look later tonight

**Comment by dcramer** [comment]
Still haven't sorted out the health check dilemmas, but closing this for now.
