### ISSUE TITLE
travis-ci.com support on zeus.ci?

### ISSUE THREAD

**Issue by LewisJEllis** [getsentry/zeus#87]
I want to take this for a spin, but readme indicates travis-ci.com is not yet supported.

Is that on the roadmap for any time soon? What's theoretically involved in adding that support? Is there an in-the-meantime workaround that wouldn't require hosting Zeus myself?

**Comment by dcramer** [comment]
There's actually support on the backend, we just need to figure out the best way to expose it in the API. Basically the Travis provider supports a domain argument, but theres currently no way to read/write that in the API.

**Comment by dcramer** [comment]
This is in the UI as of aea557bde167e95b505a42877422a652baee14c9
